SKILL_ALIASES: dict[str, str] = {
    "react.js": "react",
    "reactjs": "react",
    "node.js": "node.js",
    "nodejs": "node.js",
    "postgres": "postgresql",
    "postgresql": "postgresql",
    "aws": "aws",
    "amazon web services": "aws",
    "gcp": "gcp",
    "google cloud": "gcp",
    "azure": "azure",
    "typescript": "typescript",
    "javascript": "javascript",
    "python": "python",
    "java": "java",
    "kotlin": "kotlin",
    "go": "go",
    "golang": "go",
    "fastapi": "fastapi",
    "django": "django",
    "flask": "flask",
    "spring boot": "spring boot",
    "redis": "redis",
    "kafka": "kafka",
    "docker": "docker",
    "kubernetes": "kubernetes",
    "terraform": "terraform",
    "sql": "sql",
    "mysql": "mysql",
    "mongodb": "mongodb",
    "graphql": "graphql",
    "rest": "rest",
    "rest api": "rest",
    "microservices": "microservices",
    "ci/cd": "ci/cd",
    "machine learning": "machine learning",
    "llm": "llm",
    "openai": "openai",
    "langchain": "langchain",
    "pytorch": "pytorch",
    "tensorflow": "tensorflow",
}

ACTION_VERBS = {
    "architected",
    "built",
    "designed",
    "delivered",
    "developed",
    "implemented",
    "improved",
    "launched",
    "led",
    "migrated",
    "optimized",
    "reduced",
    "scaled",
    "shipped",
}

SECTION_ALIASES: dict[str, str] = {
    "summary": "summary",
    "professional summary": "summary",
    "profile": "summary",
    "skills": "skills",
    "technical skills": "skills",
    "core skills": "skills",
    "experience": "experience",
    "work experience": "experience",
    "professional experience": "experience",
    "employment": "experience",
    "projects": "projects",
    "project experience": "projects",
    "education": "education",
    "certifications": "certifications",
    "certification": "certifications",
    "achievements": "achievements",
    "awards": "achievements",
}

